# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/final7/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# script 실행
hooks:
  AfterInstall:
    - location: scripts/was1.sh
      timeout: 180
      runas: ec2-user

